# -*- coding: utf-8 -*-
"""apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n84_sc3qQN04gMmlo5kroDZV7ZODtfgr
"""

from mlxtend.frequent_patterns import apriori, association_rules

data = pd.read_csv('dataset.csv')

frequent_itemsets = aprior(data, min_support=0.01, use_colnames=True)

rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)