# -*- coding: utf-8 -*-
"""Bayes_Classifications.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKIw3jg-aeeW23JRQ_wIabhuJ1w16Tpe
"""

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

data = pd.read_csv('dataset.csv')

X = data.drop('targetColumn', axis=1)
y = data['targetColumn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)