# -*- coding: utf-8 -*-
"""ConfusionMatrix_F1Score_Precision_Recall_ROCCurve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XYJu1ugIG91uzznJRd-3zF1ouw39FfFN
"""

from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score, roc_curve
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

fpr, tpr, thresholds = roc_curve(y_test, y_pred)
plt.plot(fpr, tpr)
plt.show()