# -*- coding: utf-8 -*-
"""error_detection_Fixing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oiGEmZdQIkEePTvEIYj8j9k5PKFEjgt
"""

import pandas as pd
import numpy as np
data = pd.read_csv('dataset.csv')

missing_data = data.isnull().sum()

data.fillna(data.mean(), inplace=True)

a1 = data.quantile(0.25)
a2 = data.quantile(0.75)
iqr = a2 - a1
outliers = (data < ( a1 - 1.5 * iqr )) | (data > ( a2 + 1.5 * iqr ))