# -*- coding: utf-8 -*-
"""kMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojOGRm32yahXm_epjy7KFVJnAGaPnBxX
"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

data = pd.read_csv('dataset.csv')

model = KMeans(n_clusters=3)
model.fit(data)

plt.scatter(data['x'], data['y'], c=model.labels_)
plt.show()