# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1It5aM6J4PoB6hh9DOLISWwFDpsRfD3jW
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

data.pd.read_csv('dataset.csv')

X = data.drop('feature', axis=1)
y = data['targetColumn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)