# -*- coding: utf-8 -*-
"""noise_outliers_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-htJ6o4Xb49sGmWAh8LNujP1OqbJ8rov
"""

from sklearn.ensemble import IsolationForest

data = pd.read_csv('dataset.csv')

model = IsolationForest(contamination=0.01)
model.fit(data)

outliers = model.predict(data)

data['outliers'] = outliers